### PR TITLE
Add "this." prefix to all field accesses

### PR DESCRIPTION
**Pull request by Sergio0694**
This PR adds the missing `this.` prefix to all leftover field accesses.

### CODE REVIEW

**Comment by Nirmal4G** [comment]
Seeing the code, we'll know whether it's a parameter from the method or a field and a property within the class/struct. Do we have to add these? It is visually distracting. IMO, it's best to remove all `this` qualifiers unless the names of the method and parameter are the same which is rare and compiler would certainly complain about it.

So, I think it is safe to remove all `this`! On that note, we should also come up with a definite way to name fields. Whether prefixing `_` underscore is required or not. There are a lot of inconsistencies here. I vote **NO** but some .NET projects use them!

**Comment by Sergio0694** [comment]
Fields should just be named `lowerCamelCase`. The only reason why some use `_lowerCamelCase` is that they're from old classes we haven't refactored yet. I guess I might as well update those too while at it, since it's not a breaking change anyway.

> "Seeing the code, we'll know whether it's a parameter from the method or a field and a property within the class/struct. Do we have to add these? It is visually distracting."

Adding `this.` makes the code less error prone, as it avoids the risk of accidentally referencing a local or a parameter with the same name. Yes, you can manually add `this.` when there's a conflict, but that is precisely the point - making this mandatory means you don't have to rememeber, and you can't make mistakes. If there's `this`, it's 100% a field.

**Comment by Nirmal4G** [comment]
> Yes, you can manually add `this`. when there's a conflict, but that is precisely the point - making `this` mandatory means you don't have to remember, and you can't make mistakes. If there's `this`, it's 100% a field.

Guess it makes sense! Still, I personally hate it. I just use different names for parameters, locals and fields.

**Comment by Balkoth** [comment]
Theres [this](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/coding-style.md) directly from the runtime team.

**Comment by Sergio0694** [comment]
That is not the official guidance for all C# developers, just the style convention the runtime uses 🙂

**Pull request merged**
