### PR TITLE
Update Code of Conduct document

### PR DESCRIPTION
**Pull request by Nirmal4G**
## Changes

Update the Code of Conduct doc to the latest revision from .NET Foundation.
The .NET Foundation's version was last updated in 2020 which was v2.0 revision.
The latest version available from the Contributor Covenant website is v2.1 revision.

#### PermaLinks

1. .NET Foundation's CoC: <https://dotnetfoundation.org/code-of-conduct>.
2. Contributor Covenant v2.0: <https://contributor-covenant.org/version/2/0/code_of_conduct>
3. Contributor Covenant v2.1: <https://contributor-covenant.org/version/2/1/code_of_conduct>

## PR Checklist

- [x] Created a separate branch (_other than main/master_) in your fork
- [x] Based off latest main branch of toolkit
- [x] Pull Request doesn't include merge commits
- [x] Header has been added to all new source files
- [x] Contains **NO** breaking changes
- [x] Code follows all style conventions

## Other information

 - Please **Rebase** merge if possible.
 - Please update the default message option to `Default to pull request title and description` in the Repository Pull Request settings to have a better commit message instead of `Merge pull request #xxxx from repo/branch` generic message.

### CODE REVIEW

**Comment by Nirmal4G** [comment]
@michael-hawker @Sergio0694 requested for review!

**Review by michael-hawker — APPROVED** [review]
LGTM, @Sergio0694 want to take a quick look?

**Review by Sergio0694 — APPROVED** [review]
Looks good, thank you! 🙂

**Comment by michael-hawker** [comment]
@Nirmal4G appreciate your eye for staying on top of these things. Would you want to apply the same update to our [Labs repo as well](https://aka.ms/toolkit/labs/windows)? Thanks!

**Comment by Nirmal4G** [comment]
@michael-hawker Sure, will do.

**Pull request merged**
